let decTimelineElements = [
    {
        id: 1,
        title: "Opening up the month with more studying at Aliya Kanji!",
        mood: "Tired",
        location: "Aliya Kanji", 
        image: "pictures/12_01.jpg",
        description: "Working and studying with my friends at Aliya Kanji!",
        date: "12/01",
        icon: "study",
      },
      {
        id: 3,
        title: "Board games at Aliya Kanji again!",
        mood: "Tired",
        location: "Aliya Kanji", 
        image: "pictures/12_03.jpg",
        description: "Playing board games at Aliya Kanji with my friends!",
        date: "12/03",
        icon: "friends",
      },
      {
        id: 5,
        title: "Studying at Icahn Laboratory",
        mood: "Tired",
        location: "Icahn Laboratory", 
        image: "pictures/12_05.jpg",
        description: "Studying alone at Icahn Laboratory to prep for finals!",
        date: "12/05",
        icon: "study",
      },
      {
        id: 6,
        title: "Studying at Icahn for Math",
        mood: "Tired",
        location: "Aliya Kanji", 
        image: "pictures/12_06.jpg",
        description: "Studying with friends to prep for Math exam the following morning.",
        date: "12/06",
        icon: "study",
      },
      {
        id: 7,
        title: "Walking to Aliya Kanji Hall",
        mood: "Tired",
        location: "Aliya Kanji", 
        image: "pictures/12_07.jpg",
        description: "Walking to Aliya Kanji Hall to continue studying for the night.",
        date: "12/07",
        icon: "study",
      },
      {
        id: 9,
        title: "BodyHype's show: MIRAGE",
        mood: "Excited",
        location: "Frist", 
        image: "pictures/12_09.jpg",
        description: "Saw BodyHype's show! It was so fun and so mind-blowing to see what dancers can do!",
        date: "12/09",
        icon: "friends",
      },
  ];
  
export default decTimelineElements;