let novTimelineElements = [
    {
        id: 2,
        title: "November opens with friends studying at Aliya Kanji",
        location: "Aliya Kanji",
        mood: "Happy",
        image: "pictures/11_02.jpg",
        description: "Studying with friends at Aliya Kanji again!",
        date: "11/02",
        icon: "study",
      },
      {
        id: 3,
        title: "Playing mahjong with my friends!",
        location: "Frist", 
        mood: "Happy",
        image: "pictures/11_03.jpg",
        description: "Learning to play mahjong for the first time and had a lot of fun!",
        date: "11/03",
        icon: "frends",
      },
      {
        id: 4,
        title: "Board games at Aliya Kanji",
        location: "Aliya Kanji",
        mood: "Happy", 
        image: "pictures/11_04.jpg",
        description: "Studied at Aliya Kanji and played board games till very late this day.",
        date: "11/04",
        icon: "frends",
      },
      {
        id: 5,
        title: "Saw Alpaca animals!",
        location: "Alpaca Farm", 
        mood: "Happy",
        image: "pictures/11_05.jpg",
        description: "Went to go see Alpacas with my friends at an Alpaca farm near Princeton.",
        date: "11/05",
        icon: "frends",
      },
      {
        id: 6,
        title: "Late night study at Yeh dining hall",
        location: "Yeh Dining Hall", 
        mood: "Tired",
        image: "pictures/11_06.jpg",
        description: "Studied till very late in the Yeh dining hall; they had good snacks though.",
        date: "11/06",
        icon: "study",
      },
      {
        id: 9,
        title: "Late night Nassau Hall",
        location: "Nassau Hall", 
        mood: "Exhausted",
        image: "pictures/11_09.jpg",
        description: "Nassau Hall at night is very pretty, also walking back home late from a meeting on Nassau street.",
        date: "11/09",
        icon: "friends",
      },
      {
        id: 11,
        title: "Surprise Birthday party for my friend!",
        location: "Yeh Common Room",
        mood: "Happy",
        image: "pictures/11_11.jpg",
        description: "Celebrated my friends birthday at Yeh common room; we had brownie cake and was it was very fun!",
        date: "11/11",
        icon: "friends",
      },
      {
        id: 12,
        title: "Went to Yale for the weekend!",
        location: "Pizza @ Yale", 
        mood: "Hungry",
        image: "pictures/11_12.jpg",
        description: "Waited for pizza for over an hour and half, but Yale was very pretty and had very good foods!",
        date: "11/12",
        icon: "friends",
      },
      {
        id: 13,
        title: "Harry Potter on Broadway!",
        location: "Broadway", 
        mood: "Happy",
        image: "pictures/11_13.jpg",
        description: "Got to see the Harry Potter and the Cursed Child! Effects were so cool!",
        date: "11/13",
        icon: "friends",
      },
      {
        id: 14,
        title: "Another friends birthday!",
        location: "Icahn Laboratory", 
        mood: "Happy",
        image: "pictures/11_14.jpg",
        description: "Threw a surprise party for one of my friends at the Icahn Lab!",
        date: "11/14",
        icon: "friends",
      },
      {
        id: 15,
        title: "Workout BeReal",
        location: "Dillion Gym", 
        mood: "Happy",
        image: "pictures/11_15.jpg",
        description: "Working out at Dillion Gym",
        date: "11/15",
        icon: "friends",
      },
      {
        id: 17,
        title: "Workout BeReal Part 2",
        location: "Dillion Gym", 
        mood: "Exhausted",
        image: "pictures/11_17.jpg",
        description: "Working out at Dillion Gym (again)",
        date: "11/17",
        icon: "friends",
      },
      {
        id: 18,
        title: "Tons of friends, small pianom room.",
        location: "NCW Piano room",
        mood: "Exhausted",
        image: "pictures/11_18.jpg",
        description: "Hanging out with my friends in a small piano room.",
        date: "11/18",
        icon: "friends",
      },
      {
        id: 19,
        title: "Three birthdays in one month?!",
        location: "COS Classroom", 
        mood: "Happy",
        image: "pictures/11_19.jpg",
        description: "Threw another surprise birthday party for another one of my friends!",
        date: "11/19",
        icon: "friends",
      },
      {
        id: 20,
        title: "Who forgot to turn off the fountain?!",
        location: "SPIA fountain", 
        mood: "Tired",
        image: "pictures/11_20.jpg",
        description: "Saw the SPIA fountain frozen on my way to my meeting.",
        date: "11/20",
        icon: "friends",
      },
      {
        id: 21,
        title: "Whitman Courtyard in the night",
        location: "Whitman Courtyard", 
        mood: "tired",
        image: "pictures/11_21.jpg",
        description: "Saw the Whitman courtyard at night on my way back to my dorm.",
        date: "11/21",
        icon: "friends",
      },
      {
        id: 23,
        title: "Friendsgiving with amigos!",
        mood: "Happy",
        location: "Mathey Common Room", 
        image: "pictures/11_23.jpg",
        description: "Had a thanksgiving dinner with my friends at Mathey common room!",
        date: "11/23",
        icon: "friends",
      },
      {
        id: 26,
        title: "Friendsgiving with amigos! (NYC)",
        mood: "Hungry",
        location: "Laojie Hotpot", 
        image: "pictures/11_26.jpg",
        description: "Went to NYC with some of friends and had a friendsgiving at a hotpot place!",
        date: "11/26",
        icon: "friends",
      },
      {
        id: 27,
        title: "Back to the Yeh Dining Hall",
        mood: "Hungry",
        location: "Yeh Dining Hall", 
        image: "pictures/11_27.jpg",
        description: "Nice to see all of my friends again and had dinner with them at the Yeh Dining Hall.",
        date: "11/27",
        icon: "friends",
      },
      {
        id: 30,
        title: "Back to working on assignments and PSets.",
        mood: "Tired",
        location: "Joline Dorm", 
        image: "pictures/11_30.jpg",
        description: "Working in my dorm in one of the rarer ocassions.",
        date: "11/30",
        icon: "study",
      },
  ];
  
export default novTimelineElements;