let OctTimelineElements = [
    {
        id: 1,
        title: "Yeh Dining with friends!",
        location: "Yeh Dining Hall",
        mood: "Happy",
        image: "pictures/10_01.jpg",
        description: "Had dinner at the NCW/Yeh dining hall with my friends.",
        date: "10/01",
        icon: "friends",
      },
      {
        id: 2,
        title: "More studying at Whitman!",
        location: "Whitman common room",
        mood: "Tired",
        image: "pictures/10_02.jpg",
        description: "Studying with my friend at whitman common room again!",
        date: "10/02",
        icon: "study",
      },
      {
        id: 3,
        title: "Eating at NCW again!",
        location: "Yeh Dining Hall",
        mood: "Happy",
        image: "pictures/10_03.jpg",
        description: "Had dinner at the NCW/Yeh dining hall with my friends (again).",
        date: "10/03",
        icon: "friends",
      },
      {
        id: 4,
        title: "Firestone basement study again!",
        location: "Firestone",
        mood: "Tired",
        image: "pictures/10_04.jpg",
        description: "Studying at firestone C level again, different view at night though.",
        date: "10/04",
        icon: "study",
      },
      {
        id: 6,
        title: "Kung Fu Tea @ Princeton",
        location: "Kung Fu Tea",
        mood: "Happy",
        image: "pictures/10_06.jpg",
        description: "Trying Kung Fu Tea at Princeton for the first time, wasn't too bad but very expensive.",
        date: "10/06",
        icon: "friends",
      },
      {
        id: 7,
        title: "Pretty Moon @ Princeton",
        location: "Dillion Gym",
        mood: "Happy",
        image: "pictures/10_07.jpg",
        description: "Saw a very pretty moon/view outside of the Dillion Gym.",
        date: "10/07",
        icon: "friends",
      },
      {
        id: 8,
        title: "Discovering Einstein's Hall",
        location: "Einstein Hall",
        mood: "Happy",
        image: "pictures/10_08.jpg",
        description: "We found where Einstein taught at Princeton and studied there as well!",
        date: "10/08",
        icon: "study",
      },
      {
        id: 12,
        title: "COS Grind!",
        location: "COS Classroom",
        mood: "Happy",
        image: "pictures/10_12.jpg",
        description: "Cramming for an exam with the rest of my precept group!",
        date: "10/12",
        icon: "study",
      },
      {
        id: 13,
        title: "Hanging out in Whitman dorm Part 3!",
        location: "Whitman Dorm",
        mood: "Happy",
        image: "pictures/10_13.jpg",
        description: "Hanging out with friends at a whitman dorm and building lego sets!",
        date: "10/13",
        icon: "friends",
      },
      {
        id: 14,
        title: "Pumpkin Carving with friends!",
        location: "Mathey Courtyard",
        mood: "Happy",
        image: "pictures/10_14.jpg",
        description: "Post carving pumpkins and leaving them outside my Mathey dorm!",
        date: "10/14",
        icon: "friends",
      },
      {
        id: 15,
        title: "Flying back to Colorado from Jersey!",
        location: "United Aircraft",
        mood: "Exhausted",
        image: "pictures/10_15.jpg",
        description: "Heading back home on a United aircraft flight!",
        date: "10/15",
        icon: "friends",
      },
      {
        id: 19,
        title: "Heading back home in a Car with my family.",
        location: "Car",
        mood: "Happy",
        image: "pictures/10_19.jpg",
        description: "Going back home in a car! Haven't sat in a car in a while though.",
        date: "10/18",
        icon: "friends",
      },
      {
        id: 20,
        title: "Going on a small road trip with my family!",
        location: "Car",
        mood: "Tired",
        image: "pictures/10_20.jpg",
        description: "Going to Denver with family in a small road trip.",
        date: "10/20",
        icon: "friends",
      },
      {
        id: 21,
        title: "Finished shopping with my family!",
        location: "Castle Rock",
        mood: "Tired",
        image: "pictures/10_21.jpg",
        description: "Finished shopping and heading back home in Car.",
        date: "10/21",
        icon: "friends",
      },
      {
        id: 23,
        title: "Friends surprised me with Birthday party!",
        location: "COS Classroom",
        mood: "Happy",
        image: "pictures/10_23.jpg",
        description: "Came back to a pleasant surprise from my friends at the COS Classroom celebrating my birthday!",
        date: "10/23",
        icon: "friends",
      },
      {
        id: 24,
        title: "Studying with Friends at East Pyne",
        location: "East Pyne classroom",
        mood: "Happy",
        image: "pictures/10_24.jpg",
        description: "Studying with friends at a new study spot at East Pyne.",
        date: "10/24",
        icon: "study",
      },
      {
        id: 25,
        title: "Nice view of Witherspoon",
        location: "Blair Arch",
        mood: "Happy",
        image: "pictures/10_25.jpg",
        description: "Walking right outside of Rockefeller's Witherspoon residential college.",
        date: "10/25",
        icon: "friends",
      },
      {
        id: 26,
        title: "Figuring out my COS project!",
        location: "Aliya Kanji",
        mood: "Tired",
        image: "pictures/10_26.jpg",
        description: "Finally figuring out COS project after numerous hours of debugging and testing!",
        date: "10/26",
        icon: "study",
      },
      {
        id: 27,
        title: "Studying with more friends at Aliya Kanji!",
        location: "Aliya Kanji",
        mood: "Tired",
        image: "pictures/10_27.jpg",
        description: "More studying with my friends at Aliya Kanji",
        date: "10/27",
        icon: "study",
      },
      {
        id: 28,
        title: "Pool at Yeh common room.",
        location: "Yeh Common Room",
        mood: "Tired",
        image: "pictures/10_28.jpg",
        description: "Playing pool with my friends at Yeh and here's a shot of them all shooting the same ball.",
        date: "10/28",
        icon: "friends",
      },
      {
        id: 30,
        title: "Nice fall view of Princeton.",
        location: "Dillion Gym",
        mood: "Tired",
        image: "pictures/10_30.jpg",
        description: "Walking down the road next to Dillion Gym and seeing the view.",
        date: "10/30",
        icon: "study",
      },
      {
        id: 31,
        title: "Hanging with friends in Whitman common room!",
        location: "Whitman Common Room",
        mood: "Tired",
        image: "pictures/10_31.jpg",
        description: "Hanging out with friends in the common of Whitman! Not very productive work session.",
        date: "10/31",
        icon: "friends",
      },
      
      
      
  ];
  
export default OctTimelineElements;