let timelineElements = [
  {
    id: 1,
    title: "First BeReal!",
    location: "Studio 34",
    mood: "Happy",
    image: "pictures/09_01.jpg",
    description: "First Week of School! Classes haven't started and still in orientation with most of my friends!",
    date: "09/01",
    icon: "friends",
  },
  {
    id: 2,
    title: "Dorm Pic!",
    location: "Joline Dorm",
    mood: "Happy",
    image: "pictures/09_02.jpg",
    description: "Picture of my dorm and my roommate! Princeton is really hot today.",
    date: "09/02",
    icon: "friends",
  },
  {
    id: 3,
    title: "Watching a play!",
    location: "Mccarter Theatre",
    mood: "Happy",
    image: "pictures/09_03.jpg",
    description: "Outside of Mccarter Theatre. Met some more people and some zee members!",
    date: "09/03",
    icon: "friends",
  },
  {
    id: 4,
    title: "More Orientation Stuff",
    location: "Mccarter Theatre",
    mood: "Tired",
    image: "pictures/09_04.jpg",
    description: "In Mccosh 50, with the most of the class of 2026 watching a livestream of an orientation event.",
    date: "09/04",
    icon: "friends",
  },
  {
    id: 5,
    title: "First Comedy Show with Sheng Wang",
    location: "Mccarter Theatre",
    mood: "Excited",
    image: "pictures/09_05.jpg",
    description: "Watching a comedy show and Sheng Wang was so funny during the show!",
    date: "09/05",
    icon: "friends",
  },
  {
    id: 6,
    title: "Hanging out with Friends",
    location: "Whitman Dorm",
    mood: "Happy",
    image: "pictures/09_06.jpg",
    description: "Hanging out with friends at a Whitman Dorm; so much nicer than Mathey.",
    date: "09/06",
    icon: "friends",
  },
  {
    id: 7,
    title: "Mathey Common Room Event",
    location: "Mathey Common Room",
    mood: "Happy",
    image: "pictures/09_07.jpg",
    description: "Had an event at Mathey Common Room, met many students also in Mathey.",
    date: "09/07",
    icon: "friends",
  },
  {
    id: 8,
    title: "Tea Room Study!",
    location: "Tea Room",
    mood: "Happy",
    image: "pictures/09_08.jpg",
    description: "Studying with my friends at Firestone's Tea Room.",
    date: "09/08",
    icon: "study",
  },
  {
    id: 9,
    title: "Firestone Study!",
    location: "Tea Room",
    mood: "Happy",
    image: "pictures/09_09.jpg",
    description: "Studying with my friends at Firestone's Collaboration Space.",
    date: "09/09",
    icon: "friends",
  },
  {
    id: 10,
    title: "Visited CVS for the first time!",
    location: "CVS",
    mood: "Happy",
    image: "pictures/09_10.jpg",
    description: "Explored Nassau and went into a CVS at Princeton for the first time.",
    date: "09/10",
    icon: "friends",
  },
  {
    id: 11,
    title: "Super exhausted by Psets and Homework.",
    location: "Whitman Common Room",
    mood: "Exhausted",
    image: "pictures/09_11.jpg",
    description: "Studying in a common room, but super exhausted by all the Princeton work.",
    date: "09/11",
    icon: "study",
  },
  {
    id: 12,
    title: "Polaroid of a BeReal",
    location: "Whitman Common Room",
    mood: "Happy",
    image: "pictures/09_12.jpg",
    description: "Went with friends for succelents, and got a polaroid of us while taking a BeReal!",
    date: "09/12",
    icon: "friends",
  },
  {
    id: 13,
    title: "Firestone Study Part 2",
    location: "Firestone",
    mood: "Tired",
    image: "pictures/09_13.jpg",
    description: "Studying at Firestone Floor C with more friends!",
    date: "09/13",
    icon: "friends",
  },
  {
    id: 14,
    title: "Walking back to Whitman",
    location: "Whitman Courtyard",
    mood: "Tired",
    image: "pictures/09_14.jpg",
    description: "Walking back to Whitman dorm with my friend!",
    date: "09/14",
    icon: "friends",
  },
  {
    id: 15,
    title: "Eating Dinner with friends at Whitman Dining Hall",
    location: "Whitman Dining Hall",
    mood: "Tired",
    image: "pictures/09_15.jpg",
    description: "Eating Dinner with my friends after a tryout for a dance group.",
    date: "09/15",
    icon: "friends",
  },
  {
    id: 16,
    title: "Solo Practice in Studio",
    location: "Whitman Studio",
    mood: "Tired",
    image: "pictures/09_16.jpg",
    description: "Practicing dance by myself in Whitman dance studio.",
    date: "09/16",
    icon: "friends",
  },
  {
    id: 17,
    title: "More Studying with Friends!",
    location: "Whitman Common Room",
    mood: "Happy",
    image: "pictures/09_17.jpg",
    description: "Studying more with friends at the Whitman Common Room!",
    date: "09/17",
    icon: "study",
  },
  {
    id: 18,
    title: "More Studying with Friends! Part 2",
    location: "Whitman Common Room",
    mood: "Happy",
    image: "pictures/09_18.jpg",
    description: "Studying more with friends at the Whitman Common Room! (Again)",
    date: "09/18",
    icon: "study",
  },
  {
    id: 19,
    title: "More Studying at Firestone!",
    location: "Firestone",
    mood: "Happy",
    image: "pictures/09_19.png",
    description: "Studying more with friends at the top floor of Firestone.",
    date: "09/19",
    icon: "study",
  },
  {
    id: 20,
    title: "Discovered a new study spot at Frist",
    location: "Frist",
    mood: "Tired",
    image: "pictures/09_20.png",
    description: "Discovered a new study spot and just had a meeting in this room at Frist.",
    date: "09/20",
    icon: "study",
  },
  {
    id: 21,
    title: "Hanging out with friends late!",
    location: "Whitman Common Room",
    mood: "Happy",
    image: "pictures/09_21.jpg",
    description: "Hanging out with friends at Whitman common room!",
    date: "09/21",
    icon: "friends",
  },
  {
    id: 22,
    title: "Late meal at new study spot.",
    location: "Frist",
    mood: "Happy",
    image: "pictures/09_22.png",
    description: "Enjoying late meal at my new study spot with double selfie BeReal.",
    date: "09/22",
    icon: "friends",
  },
  {
    id: 23,
    title: "First time trying out Forbes Dinner",
    location: "Forbes Dining Hall",
    mood: "Happy",
    image: "pictures/09_23.jpg",
    description: "Trying out Forbes dinner with my friends! Wasn't too bad (goes downhill from here).",
    date: "09/23",
    icon: "friends",
  },
  {
    id: 24,
    title: "Leyton's Birthday at Whitman's common Room",
    location: "Whitman Common Room",
    mood: "Happy",
    image: "pictures/09_24.jpg",
    description: "Celebrating Leyton's birthday at Whitman's common room.",
    date: "09/24",
    icon: "friends",
  },
  {
    id: 25,
    title: "Sympoh Pickups!",
    location: "Dillion Gym",
    mood: "Happy",
    image: "pictures/09_25.png",
    description: "Getting picked up for Sympoh and got meet tons of new Breakers!",
    date: "09/25",
    icon: "friends",
  },
  {
    id: 26,
    title: "Pretty Firestone Grind",
    location: "Firestone",
    mood: "Tired",
    image: "pictures/09_26.png",
    description: "Studying at Firestone again, but very nice view when I look up.",
    date: "09/26",
    icon: "study",
  },
  {
    id: 28,
    title: "More Studying at Whitman common room.",
    location: "Whitman Common Room",
    mood: "Tired",
    image: "pictures/09_28.png",
    description: "Studying at whitman common room with more friends!",
    date: "09/28",
    icon: "study",
  },
  {
    id: 29,
    title: "Blair Arch is good looking.",
    location: "Blair Arch",
    mood: "Tired",
    image: "pictures/09_29.png",
    description: "A nice picture of Blair Arch as I'm walking down it.",
    date: "09/29",
    icon: "friends",
  },
  {
    id: 30,
    title: "First instance of studying at Aliya Kanji",
    location: "Aliya Kanji",
    mood: "Happy",
    image: "pictures/09_30.jpg",
    description: "First time I discovered Aliya Kanji and studying in with my friends!",
    date: "09/30",
    icon: "study",
  },
  
];

export default timelineElements;
