let timelineElements = [
  {
    id: 1,
    title: "First Week at Princeton!",
    location: "Studio 34, Joline Dorm, Mccarter Theatre, Mccosh 50, Whitman Dorm",
    mood: "Happy x4, Tired, Excited",
    image: "week/Week 09_01-09_06.png",
    description: "First Week of School! Classes haven't started and still in orientation with most of my friends!",
    date: "09/01-09/06",
    icon: "friends",
  },
  {
    id: 2,
    title: "Classes Start!",
    location: "Mathey Common Room, Tea Room, Firestone, CVS, Whitman Common Room x2",
    mood: "Happy x5, Exhausted",
    image: "week/Week 09_07-09_012.png",
    description: "Classes have started and I'm feeling what it's like to be a Princeton student. Schoolwork is hard, but friends are what make it worth it",
    date: "09/07-09/12",
    icon: "friends",
  },
  {
    id: 3,
    title: "Princeton Grind!",
    location: "Firestone, Whitman Courtyard, Whitman Dining Hall, Whitman Studio, Whitman Common Room x2",
    mood: "Happy x4, Tired x2",
    image: "week/Week 09_13-09_18.png",
    description: "Adjusting to Princeton and hanging out with more friends! Started to join dance groups/clubs here",
    date: "09/13-09/18",
    icon: "school",
  },
  {
    id: 4,
    title: "Discovering new places!",
    location: "Firestone, Frist x2, Whitman Common Room x2, Forbes Dining Hall",
    mood: "Happy x5, Tired",
    image: "week/Week 09_19-09_25.png",
    description: "Discovered Frist and Forbes. Same old Princeton work and study.",
    date: "09/19-09/25",
    icon: "friends",
  },
  {
    id: 5,
    title: "More Princeton Grind + Niki concert!",
    location: "Dillion Gym, Firestone, Webster Hall, Whitman Common Room, Blair Arch, Aliya Kanji",
    mood: "Happy x2, Tired x3, Excited",
    image: "week/Week 09_26-10_01.png",
    description: "Same Princeton grind as usual. Pretty architecture with Firestone and Blair Arch. Also went to NYC for the first time!",
    date: "09/26-10/01",
    icon: "school",
  },
  {
    id: 6,
    title: "First time trying boba at Princeton, more studying! ",
    location: "Aliya Kanji, Yeh Dining Hall x2, Whitman Common Room, Yeh Dining Hall, Firestone, Kung Fu Tea",
    mood: "Happy x3, Tired x2",
    image: "week/Week 10_02-10_08.png",
    description: "Tried boba at Princeton for the first time! More studying at obsecure places like Einstein Lecture Room and we had a pretty moon one day.",
    date: "10/02-10/08",
    icon: "friends",
  },
  {
    id: 7,
    title: "End of the Princeton grind pt1, slight start to fall break.",
    location: "Sinclair's Backyard, COS Classroom, Whitman Dorm, Mathey Courtyard, United Aircraft, Mika Sushi",
    mood: "Happy x3, Tired, Excited x2",
    image: "week/Week 10_10-10_16.png",
    description: "Finishing up midterms here and carved pumpkins with my friends! Also headed back home for fall break and had sushi on the day I came back.",
    date: "10/10-10/06",
    icon: "school",
  },
  {
    id: 7,
    title: "Fall break at Colorado, come back to birthday surprise!",
    location: "Boulder Classroom, Car x2, Castle Rock, FunnyPlus, COS Classroom",
    mood: "Happy x3, Tired x3",
    image: "week/Week 10_18-10_23.png",
    description: "Enjoying the rest of my fall break with my friends back home. I come back to my friends throwing me a surprise brithday party.",
    date: "10/18-10/23",
    icon: "friends",
  },
  {
    id: 8,
    title: "Back on Princeton grind + Princetoween!",
    location: "East Pyne Classroom, Blair Arch, Aliya Kanji, Aliya Kanji, Yeh Common Room, Prospect",
    mood: "Happy, Tired x5",
    image: "week/Week 10_24-10_29.png",
    description: "Getting back into studying and doing work again after a restful break. First Princetoween at Princeton.",
    date: "10/24-10/29",
    icon: "school",
  },
  {
    id: 9,
    title: "Board games, Mahjong, and friends!",
    location: "Dillion Gym, Whitman Common Room, Aliya Kanji, Mathey, Frist, Aliya Kanji",
    mood: "Happy x3, Tired x3",
    image: "week/Week 10_30-11_04.png",
    description: "Getting back into studying and doing work again after a restful break. First Princetoween at Princeton.",
    date: "10/30-11/04",
    icon: "friends",
  },
  {
    id: 10,
    title: "Exploration!",
    location: "Alpaca Farm, Yeh Dining Hall, Nassau Hall, Yeh Common Room, Pizza @Yale, Broadway",
    mood: "Happy x3, Tired, Exhausted, Hungry",
    image: "week/Week 11_05-11_13.png",
    description: "Went to Alpaca farms, saw Nassau Hall, celebrated friends birthday, went to Yale, and Harry potter show on Broadway!",
    date: "11/05-11/13",
    icon: "friends",
  },
  {
    id: 11,
    title: "More birthdays, Gym, and Sympoh!",
    location: "Icahn Laboratory, Dillion Gym x2, Murphy Studio, Yeh Common Room, COS Classroom",
    mood: "Happy x3, Exhausted x3",
    image: "week/Week 11_14-11_19.png",
    description: "Celebrated three more birthdays (one not shown) and back in Dillon Gym!",
    date: "11/14-11/19",
    icon: "friends",
  },
  {
    id: 12,
    title: "Thanksgiving break with x3 friendsgiving",
    location: "SPIA Fountain, Whitman Courtyard, Mathey Common Room, Laojie Hotpot, Yeh Dining Hall",
    mood: "Happy x3, Exhausted x3",
    image: "week/Week 11_20-11_27.png",
    description: "Had way too many thanksgiving dinners, but enjoyed staying on campus for break!",
    date: "11/20-11/27",
    icon: "friends",
  },
];

export default timelineElements;
